### ISSUE TITLE
Big vs. little endian

### ISSUE THREAD

**Issue by cweiske** [MatrixEditor/frontier-smart-api#3]
In docs/firmware-2.0.md#11-header-structure you write

> All numbers are little endian

When writing the [magic file line](https://bugs.astron.com/view.php?id=390) for detecting them, I noticed that I had to use the `belong` (big endian long) type:
```
0 belong 0x76110000 Frontier Silicon firmware download
```

Do you have an idea why I have to use big endian for the `file` magic database, but you say it's all little endian?

**Comment by MatrixEditor** [comment]
When looking at the header section in the firmware binaries, the first 12 bytes can be represented with Big **and** Little endian encoding. For example, we take the binary of `ir-mmi-FS2026-0500-0805.2.14.22c.EX76174-1A13`:

                 ┌─────────────────────────────────────────┐
    Offset (hex) │ 00 01 02 03 04 05 06 07 08 09 0A 0B ... │
                 ├─────────────────────────────────────────┤
     0000 0000   │ 76 11 00 00│7C 00 00 00│01 00 00 00 ... │
                 └─────────────────────────────────────────┘

The number that can be represented through each block  after the signature won't change if Big or Little endian encoding is used: 

    0x7C000000 in Big Endian encoding == 0x7C000000 in Little Endian Encoding

I assumed that these numbers are little endian, because all following numbers (compression fields and directory archive entries) are stored with the little endian encoding. Did you try your given `belong` magic number for detection? If all values are stored with little endian the signature would be the following when working with big endian:

    lelong  sigLE = 0x76110000
    belong sigBE = 0x00001176 (assuming little endian encoding as the base)
    
    lelong  sigLE = 0x00001176
    belong sigBE = 0x76110000 (assuming big endian encoding as the base)
 
In my implementation of the `ISUInspector` I used the little endian encoding for all numbers stored in the binary files ([declared here](https://github.com/MatrixEditor/frontier-smart-api/blob/main/fsapi/isu/ioutils.py)).
